language: python
python:
  - "2.7"
   # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"

install:
    - pip install -r requirements.txt

#sudo: false

env:
  - DJANGO_VERSION=1.11

services:
  - postgresql

before_script:
  - psql -c 'create database myproject;' -U postgres