language: python
python:
  - "2.7"
   # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"

install:
    - pip install -r requirements.txt

#sudo: false

env:
  - CRUD

services:
  - postgresql

script: pytest

before_script:
  - psql -c 'create database myproject;' -U postgres