language: python
python:
  - "2.7"
  - "3.6"
install:
    - pip install -r requirements.txt

sudo: false

env:
  - CRUD

services:
  - postgresql

script: ./manage.py

before_script:
  - psql -c 'create database crudapi;' -U postgres

notifications:
  email: false