language: python
python:
  - "2.7"

install:
    - pip install -r requirements.txt

sudo: false

env:
  - CRUD

services:
  - postgresql

script: ./manage.py

before_script:
  - psql -c 'create database myproject;' -U postgres

notifications:
  email: false