version: "3.0"
# CONTAINERS

volumes:
  postgres_data: {}
  postgres_backup: {}
  static: {}
  allcode: 

services:


  db:
    build: ./docker_config/postgres/
    container_name: postgres01
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/var/lib/postgresql/data
    env_file: .env


  django:
    build:
      context: .
      dockerfile: ./docker_config/django/development/Dockerfile
    container_name: dango01
    volumes:
      - .:/code
      - static:/my_cdn
    expose: 
      - "8000"
    ports:
      - "8000:8000"
    env_file: .env
    entrypoint: "./docker_config/django/development/d_start.sh"
    depends_on:
      - db
  
  node:
    build:
      context: .
      dockerfile: ./docker_config/node/development/Dockerfile
    container_name: node_server
    volumes:
      - .:/code
    command: "/n_start.sh"
    ports:
      - "3000:3000"
    depends_on:
      - django

  myadminer:
    image: adminer
    container_name: adminer01
    ports:
      - "9000:8080"
    links:
      - db