version: "3.4"
# CONTAINERS PRODUCTION
# TO DEPLOY: 
  # docker-compose  -f docker-compose.prod.yml up -d

services:


  db:
    image: "postgres:latest"
    container_name: ps01
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres

  cache:
    environment:
      TTL: '500'

  node:
    image: node:6-slim
    container_name: node01
    volumes:
      - /usr/src/app
    expose: 
      - "7777"

  django:
    build: .
    container_name: dg01
    volumes:
      - .:/code
      - /my_cdn:/my_cdn
    expose: 
      - "8000"
    entrypoint: ./start.sh
    links:
      - db
      - node
    depends_on:
      - db
      - node
    environment:
      PRODUCTION: 'true'
      DEBUG: 'false'
  

  nginx:
    image: nginx:latest
    container_name: ng01
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8000:8000"
    domainname: foo.com
    hostname: foo
    links:
        - django
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - /my_cdn:/my_cdn
    depends_on:
      - django
