version: "3.0"

services:

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    
    links:
        - django
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - /my_cdn:/my_cdn
  
    depends_on:
      - django

  db:
    image: "postgres:latest"
    container_name: ps01
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  django:
    build: .
    container_name: dg01
    volumes:
      - .:/code
      - /my_cdn:/my_cdn
    expose: 
      - "8000"
    entrypoint: ./start.sh
    links:
      - db  
    depends_on:
      - db
  