version: "3.0"
# CONTAINERS

volumes:
  postgres_data: {}
  postgres_backup: {}
  static: {}
  allcode: 

services:


  db:
    build: ./docker_config/postgres/
    container_name: postgres01
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/var/lib/postgresql/data
    env_file: .env


  django:
    build:
      context: .
      dockerfile: ./docker_config/django/development/Dockerfile
    container_name: dango01
    volumes:
      - .:/code
      - static:/my_cdn
    expose: 
      - "8000"
    env_file: .env
    entrypoint: "./docker_config/django/development/d_start.sh"
    command: "./docker_config/node/development/n_start.sh"
    env_file: .env
    links:
      - db      
    depends_on:
      - db
  
  node:
    build:
      context: .
      dockerfile: ./docker_config/node/development/Dockerfile
    container_name: node_server
    volumes:
      - .:/code
    command: "/n_start.sh"

    ports:
      - "3000:3000"
    depends_on:
      - django


  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "0.0.0.0:80:80"
    links:
        - django
    
    volumes:
      - ./docker_config/nginx:/etc/nginx/conf.d
      - /my_cdn:/my_cdn
    depends_on:
      - django

