version: "3.4"
# CONTAINERS PRODUCTION
# TO DEPLOY: 
  # docker-compose  -f docker-compose.prod.yml up -d

volumes:
  postgres_data: {}
  postgres_backup: {}
  static: {}
  allcode:

services:

  
  db:
    image: "postgres:latest"
    container_name: postgres01
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/var/lib/postgresql/data
    env_file: .env




  django:
    build:
      context: .
      dockerfile: ./docker_config/django/development/Dockerfile
    container_name: dango01
    volumes:
      - .:/code
      - /my_cdn:/my_cdn
    expose: 
      - "8000"
    entrypoint: "./docker_config/django/development/d_start.sh"
    links:
      - db
    depends_on:
      - db
    env_file: .env
    

  

  
  nginx:
    build:
      context: .
      dockerfile: ./docker_config/nginx/Dockerfile
    container_name: nginx_server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "80:80"
    links:
        - django
    volumes:
      - ./docker_config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/code
    depends_on:
      - django