version: "3.0"
# CONTAINERS

volumes:
  postgres_data: {}
  postgres_backup: {}


services:


  db:
    build: ./docker_config/postgres/
    container_name: postgres01
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/var/lib/postgresql/data
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres



  node:
    build: ./docker_config/node/    
    container_name: node01
    volumes:
      - /usr/src/app
    expose: 
      - "7777"
    ports:
      - "7777:7777"
    links:
      - django
    depends_on:
      - django
  


  django:
    build: ./docker_config/django/Development
    container_name: dango01
    volumes:
      - .:/code
      - /my_cdn:/my_cdn
    expose: 
      - "8000"
    env_file: .env
    entrypoint: ./docker_config/django/Development/start.sh
    environment:
      DEBUG: 'true'
    links:
      - db      
    depends_on:
      - db
  

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "0.0.0.0:8000:8000"
    links:
        - django
    volumes:
      - .:/code
      - ./docker_config/nginx:/etc/nginx/conf.d
      - /my_cdn:/my_cdn
    depends_on:
      - django

