version: "3.0"

services:

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8001:8000"
    expose:
      - "8001"
    links:
        - django
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - .:/usr/share/nginx/html
    depends_on:
      - django

  db:
    image: "postgres:alpine"
    container_name: ps01
  
  django:
    build: .
    container_name: dg01
    volumes:
      - .:/code

    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && ./start.sh"  
    depends_on:
      - db
  